name: Feature Request
about: Propose a change
body:
  - type: textarea
    attributes:
      label: Motivation
  - type: textarea
    attributes:
      label: Proposal
  - type: textarea
    attributes:
      label: Alternatives
