
[package]
name = "sense-bench"
version = "0.0.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"
description = "benchmarks (skeleton)"

[dev-dependencies]
criterion = "0.7.0"
rusta-sense = { path = "../rusta-sense" }
