[package]
name = "trainingcore"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
burn.workspace = true
serde.workspace = true
tracing.workspace = true
bytecore = { path = "../bytecore" }
