
[package]
name = "sense-ffi"
version = "0.0.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"
description = "C ABI (skeleton)"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.29.0"

[dependencies]
rusta-sense = { path = "../rusta-sense" }
