[package]
name = "eval-harness"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
serde.workspace = true
protocol.workspace = false
protocol = { path = "../protocol" }
tracing.workspace = true
