[package]
name = "orchestrator"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
tracing.workspace = true
protocol = { path = "../protocol" }
policy = { path = "../policy" }
