[package]
name = "orchestrator"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
policy = { path = "../policy" }
protocol = { path = "../protocol" }
