[package]
name = "rusta-conductor"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
rusta-common = { path = "../rusta-common" }
serde = { workspace = true }
anyhow = { workspace = true }
